- name: ensure secret destination folders exist
  command: mkdir -p {{item.dest | dirname}}
  args:
    creates: "{{item.dest | dirname}}"
  with_items: secret_files

- name: copy files from secret server to remote via local machine
  sudo: false
  local_action: |
    shell scp -3 -r \
    {{disable_host_key_checking | default("")}} \
    {{secret_user}}@{{secret_server}}:{{secret_path}}/{{item.src}} \
    {{secret_user}}@{{site_fqdn}}:~/
  args:
    creates: "~{{item.src}}"
  with_items: secret_files

- name: move secrets on remote machine to destination
  command: mv ~{{secret_user}}/{{item.src}} {{item.dest}}
  args:
    creates: "{{item.dest}}"
  with_items: secret_files

- name: read secrets
  sudo: false
  local_action: |
    shell ssh {{secret_user}}@{{secret_server}} cat {{secret_path}}/{{item.src}}
  register: read_secrets
  with_items: secret_vars

- name: assign secrets to facts
  set_fact: "{{item.item.dest}}=\"{{item.stdout}}\""
  with_items: read_secrets.results
  no_log: true
