- name: read secrets
  become: false
  local_action: |
    shell ssh {{secret_user}}@{{secret_server}} cat {{secret_path}}/{{item.src}}
  register: read_secrets
  with_items: secret_vars

- name: assign secrets to facts
  set_fact: "{{item.item.dest}}=\"{{item.stdout}}\""
  with_items: read_secrets.results
  no_log: true

# beware, ye who enter here and think these ansible conditionals could be
# made easier. if you'd like to dump some time into this bullshit, talk to
# tyler first for a tale of woe and some guidance.
- name: set rds environment variables for ansible 1x
  set_fact:
    DB_HOST: "{{(RDS_DB_SECRETS|from_json).host}}"
    DB_USER: "{{(RDS_DB_SECRETS|from_json).user}}"
    DB_NAME: "{{(RDS_DB_SECRETS|from_json).database}}"
    DB_PASSWORD: "{{(RDS_DB_SECRETS|from_json).password}}"
    EMAIL_KEY: "{{(EMAIL|from_json).key}}"
    EMAIL_SECRET: "{{(EMAIL|from_json).secret}}"
  when: ansible_version.major < 2
  no_log: true

- name: set rds environment variables for ansible 2x
  set_fact:
    DB_HOST: "{{RDS_DB_SECRETS.host}}"
    DB_USER: "{{RDS_DB_SECRETS.user}}"
    DB_NAME: "{{RDS_DB_SECRETS.database}}"
    DB_PASSWORD: "{{RDS_DB_SECRETS.password}}"
    EMAIL_KEY: "{(EMAIL.key}}"
    EMAIL_SECRET: "{{EMAIL.secret}}"
  when: ansible_version.major > 1
  no_log: true
